"""Paired comparison of local MUSIC and local MUSIC+ML AoA refinements.

Both methods use the same Angle-FFT range/angle candidate detector.  They only
differ in the local refinement applied to the selected range bin: MUSIC peak
interpolation versus MUSIC followed by variable-projection ML/NLS.  The
downstream displacement filter and frozen geometry beta are identical; no
beta feedback is run.
"""
from __future__ import annotations

import argparse
import csv
from dataclasses import replace
from pathlib import Path
from typing import Optional

import numpy as np

from .evaluate import evaluate_scenario
from .method_registry import all_method_specs
from .scenarios import build_phase1_scenarios


def run(output: Path, angle_output: Optional[Path] = None) -> None:
    specs = {spec.name: spec for spec in all_method_specs()}
    local_music = specs["selected_aoa_fixed_beta"]
    local_music_ml = specs["direct_aoa_fixed_beta"]
    rows = []
    angle_rows = []
    for scenario in build_phase1_scenarios(include_measured_bridge=False):
        # Candidate bins are generated by the same Angle-FFT map in both runs;
        # only target extraction/refinement changes below.
        music_scenario = replace(scenario, frontend_angle_estimation_method="local_music")
        ml_scenario = replace(scenario, frontend_angle_estimation_method="local_music_ml")
        music_rows, music_artifacts = evaluate_scenario(music_scenario, method_specs=(local_music,))
        ml_rows, ml_artifacts = evaluate_scenario(ml_scenario, method_specs=(local_music_ml,))
        for label, row, artifacts in (
            ("angle_fft_local_music", music_rows[0], music_artifacts),
            ("angle_fft_local_music_ml", ml_rows[0], ml_artifacts),
        ):
            angle_errors = np.asarray(
                [item["angle_error_deg"] for item in artifacts["frontend_aoa_diagnostics"]
                 if int(item.get("reference_idx", -1)) >= 0 and np.isfinite(item.get("angle_error_deg", np.nan))],
                dtype=float,
            )
            rows.append(
                {
                    "scenario": scenario.scenario_name,
                    "method": label,
                    "rmse_mm": float(row["rmse_mm"]),
                    "angle_rmse_deg": float(np.sqrt(np.mean(angle_errors**2))) if angle_errors.size else float("nan"),
                }
            )
            for item in artifacts["frontend_aoa_diagnostics"]:
                if int(item.get("reference_idx", -1)) < 0:
                    continue
                angle_rows.append(
                    {
                        "scenario": scenario.scenario_name,
                        "method": label,
                        "target_index": int(item["reference_idx"]),
                        "true_angle_deg": float(item["true_angle_deg"]),
                        "estimated_angle_deg": float(item["measured_angle_deg"]),
                        "angle_error_deg": float(item["angle_error_deg"]),
                    }
                )

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=("scenario", "method", "rmse_mm", "angle_rmse_deg"))
        writer.writeheader()
        writer.writerows(rows)
    angle_output = angle_output or output.with_name("direct_aoa_angle_comparison.csv")
    with angle_output.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=("scenario", "method", "target_index", "true_angle_deg", "estimated_angle_deg", "angle_error_deg"),
        )
        writer.writeheader()
        writer.writerows(angle_rows)

    for method in ("angle_fft_local_music", "angle_fft_local_music_ml"):
        values = np.asarray([r["rmse_mm"] for r in rows if r["method"] == method], dtype=float)
        print(f"{method}: mean={np.mean(values):.6f} mm, median={np.median(values):.6f} mm, max={np.max(values):.6f} mm")
    print(f"saved: {output}")
    print(f"saved: {angle_output}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("simulation/outputs/direct_aoa_comparison.csv"))
    parser.add_argument("--angle-output", type=Path, default=None)
    args = parser.parse_args()
    run(args.output, args.angle_output)


if __name__ == "__main__":
    main()
